### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by aoishik** [diliprk/VedicAstro#2]
Traceback (most recent call last):
  File "c:\Users\Aoishik\OneDrive\Desktop\LAB\astropy\a.py", line 1, in <module>
    from vedicastro.VedicAstro import VedicHoroscopeData
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\vedicastro\VedicAstro.py", line 28, in <module>
    AYANAMSA_MAPPING = { "Lahiri": const.AY_LAHIRI, "Lahiri_1940" : const.AY_LAHIRI_1940,
                                   ^^^^^^^^^^^^^^^
AttributeError: module 'flatlib.const' has no attribute 'AY_LAHIRI'

**Comment by diliprk** [comment]
Did you install the particular version of flatlib in my git, mentioned in the `requirements.txt` ?
https://github.com/diliprk/VedicAstro/blob/9a1ceab571ddf622f3a9259a6752a711bdfa7690/requirements.txt#L8

**Comment by aoi2010** [comment]
After installing it this is coming-
Traceback (most recent call last):
  File "c:\Users\Aoishik\OneDrive\Desktop\LAB\astropy\a.py", line 1, in <module>
    from vedicastro.VedicAstro import VedicHoroscopeData
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\vedicastro\VedicAstro.py", line 2, in <module>
    from flatlib.chart import Chart
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\chart.py", line 26, in <module>
    from .ephem import ephem, swe
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\ephem\__init__.py", line 15, in <module>        
    from . import swe
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\ephem\swe.py", line 56, in <module>
    const.AY_LAHIRI_1940: swisseph.SIDM_LAHIRI_1940,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'swisseph' has no attribute 'SIDM_LAHIRI_1940'. Did you mean: 'SIDM_LAHIRI'?
PS C:\Users\Aoishik\OneDrive\Desktop\LAB\astropy> & C:/Users/Aoishik/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Aoishik/OneDrive/Desktop/LAB/astropy/a.py
Traceback (most recent call last):
  File "c:\Users\Aoishik\OneDrive\Desktop\LAB\astropy\a.py", line 1, in <module>
    from vedicastro.VedicAstro import VedicHoroscopeData
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\vedicastro\VedicAstro.py", line 2, in <module>
    from flatlib.chart import Chart
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\chart.py", line 26, in <module>
    from .ephem import ephem, swe
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\ephem\__init__.py", line 15, in <module>        
    from . import swe
  File "C:\Users\Aoishik\AppData\Local\Programs\Python\Python311\Lib\site-packages\flatlib\ephem\swe.py", line 56, in <module>
    const.AY_LAHIRI_1940: swisseph.SIDM_LAHIRI_1940,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'swisseph' has no attribute 'SIDM_LAHIRI_1940'. Did you mean: 'SIDM_LAHIRI'?

**Comment by aoishik** [comment]
Error is solved. Thanks.

**Comment by diliprk** [comment]
Not sure what version of flatlib and pyswisseph you installed, I am using my own fork of flatlib which you have to install, I have specified the command for this in the Readme.md file itself, you have to use a virtual environment

**Comment by aoishik** [comment]
I installed it in global. Done. Thanks for help,
